/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zhanghuan_cn_jnitest1_MainActivity */

#ifndef _Included_zhanghuan_cn_jnitest1_MainActivity
#define _Included_zhanghuan_cn_jnitest1_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zhanghuan_cn_jnitest1_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zhanghuan_cn_jnitest1_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
